import { Plus } from "lucide-react";
import type { Metadata } from "next";
import React from "react";
import CharacterDialog from "../../components/character-dialog";
import AppBar from "../../components/ui/app-bar";
import { Button } from "../../components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div className={"flex flex-col"}>
      <AppBar>
        <CharacterDialog>
          <Button variant={"ghost"}>
            <span>Add</span>
            <Plus />
          </Button>
        </CharacterDialog>
      </AppBar>
      {children}
    </div>
  );
};

export default Layout;
